In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 5, 7, 9])
print(a)

[1 2 5 7 9]


In [4]:
print(np.min(a))

1


In [5]:
print(np.max(a))

9


In [6]:
print(np.argmin(a))

0


In [7]:
print(np.sqrt(a))

[1.         1.41421356 2.23606798 2.64575131 3.        ]


In [8]:
print(np.sin(a))

[ 0.84147098  0.90929743 -0.95892427  0.6569866   0.41211849]


In [9]:
print(np.cos(a))

[ 0.54030231 -0.41614684  0.28366219  0.75390225 -0.91113026]


In [10]:
print(np.cumsum(a))

[ 1  3  8 15 24]


In [11]:
b = np.array([[3,4,6],[6,1,2]])
print(np.min(b, axis=1))

[3 1]


In [12]:
print(np.max(b, axis=0))

[6 4 6]


In [13]:
print(np.cumsum(b))

[ 3  7 13 19 20 22]
