In [1]:
import numpy as np 

In [4]:
a = ([1, 2, 4, 5, 6, 7])
b = ([2, 4, 7, 9, 2, 8])
arr = np.add(a,b)
arr

array([ 3,  6, 11, 14,  8, 15])

In [5]:
var = np.array([2, 3, 5, 6, 8])
varadd = var + 3
print(varadd)

[ 5  6  8  9 11]


In [6]:
var1 = np.array([[1, 2, 4, 5], [2, 4, 5, 6]])
var2 = np.array([[2, 3, 5, 6], [2, 5, 7, 8]])
arr1 = np.add(var1, var2)
arr1

array([[ 3,  5,  9, 11],
       [ 4,  9, 12, 14]])

In [7]:
var3 = np.array([[[1, 2, 3, 4], [2, 4, 6, 7], [2, 3, 4, 6]]])
var4 = np.array([[[2, 3, 4, 7], [2, 4, 1, 8], [4, 5, 6, 7]]])
arr2 = np.add(var3, var4)
arr2

array([[[ 3,  5,  7, 11],
        [ 4,  8,  7, 15],
        [ 6,  8, 10, 13]]])

In [9]:
var5 = np.array([[2, 3, 4],[2, 5, 6]])
var6 = np.array([[2, 4, 6],[2, 3, 7]])
arr3 = np.add(var5, var6)
arr3

array([[ 4,  7, 10],
       [ 4,  8, 13]])

In [11]:
arr4 = np.subtract(var5, var6)
arr4

array([[ 0, -1, -2],
       [ 0,  2, -1]])

In [12]:
arr5 = np.multiply(var5, var6)
arr5

array([[ 4, 12, 24],
       [ 4, 15, 42]])

In [13]:
arr6 = np.divide(var5, var6)
arr6

array([[1.        , 0.75      , 0.66666667],
       [1.        , 1.66666667, 0.85714286]])

In [14]:
arr7 = np.mod(var5, var6)
arr7

array([[0, 3, 4],
       [0, 2, 6]])