In [2]:
import numpy as np

In [15]:
x = np.array([1, 2, 3,4])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [6]:
y = [1, 2, 3, 4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [11]:
a = np.array([2, 4, 5])
print(a)

             


[2 4 5]


In [14]:
A = []
for i in range(1, 5):
    int_1 =int(input("enter a value :"))
    A.append(int_1)
print(np.array(A))   

enter a value : 34
enter a value : 12
enter a value : 56
enter a value : 78


[34 12 56 78]


In [16]:
ar2 = np.array([[1, 2, 3, 4], [4, 9, 8, 5]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [4 9 8 5]]
2


In [18]:
ar3 = np.array([[[2, 3, 4], [5, 6, 7], [4, 9, 23]]])
print(ar3)
print(ar3.ndim)

[[[ 2  3  4]
  [ 5  6  7]
  [ 4  9 23]]]
3


In [22]:
arn = np.array([1, 4, 6, 9],ndmin = 12)
print(arn)
print(type(arn))

[[[[[[[[[[[[1 4 6 9]]]]]]]]]]]]
<class 'numpy.ndarray'>
