In [3]:
import numpy as np

## shuffle

In [4]:
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[3 1 2 5 4]


## unique

In [5]:
var1 = np.array([2,5,8,4,2,2,4,9,8])
x = np.unique(var1)
print(x)


[2 4 5 8 9]


## resize

In [9]:
var2 = np.array([2,5,8,4,2,2,4,9,8])
y = np.resize(var2,(3,2))
print(y)

[[2 5]
 [8 4]
 [2 2]]
