## search 

In [4]:
import numpy as np

In [7]:
a = np.array([3, 5, 7, 8, 12, 2, 4, 3,6]) 
print(a)
x = np.where(a == 2)
print(x)
y = np.where((a %  2 ) == 0)
print(y)

[ 3  5  7  8 12  2  4  3  6]
(array([5]),)
(array([3, 4, 5, 6, 8]),)


## sort

In [8]:
b = np.array([2, 1,5,66,8,3,9,6,10])

print(np.sort(b))

[ 1  2  3  5  6  8  9 10 66]


In [16]:
string = np.array(["a", "j", "w","q","b"])
print(np.sort(string))

['a' 'b' 'j' 'q' 'w']


In [18]:
array2 = np.array([[11,2],[51,8],[21,1]])
print(np.sort(array2))

[[ 2 11]
 [ 8 51]
 [ 1 21]]


## filter 

In [20]:
var = np.array([2,5,8,9])
f = [True, False, True,True]
new_a = var[f]
print(new_a)
print(type(new_a))

[2 8 9]
<class 'numpy.ndarray'>
