In [3]:
import numpy as np
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)




[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones


In [6]:
ar_one = np.ones(5)
ar_one1 = np.ones((3,5))
print(ar_one)
print()
print(ar_one1)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# empty

In [7]:
arr_empty = np.empty((3,7))
print(arr_empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.33511290e-306
  6.23058368e-307 8.45593934e-307 7.56593017e-307]
 [1.11258854e-306 1.11261502e-306 1.42410839e-306 7.56597770e-307
  6.23059726e-307 1.05700345e-307 2.22523140e-306]
 [1.02360867e-306 1.86921958e-306 6.89804133e-307 1.11261162e-306
  8.34443015e-308 2.22813476e-312 0.00000000e+000]]


# range element

In [12]:
arr_rn = np.arange(4)
arr_rn1 = np.arange(4,5)

print(arr_rn)
print()
print(arr_rn1)

[0 1 2 3]

[4]


# diagonal

In [14]:
ar_dia = np.eye(4)
ar_dia1 = np.eye(3,5)
print(ar_dia)
print()
print(ar_dia1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# special

In [16]:
ar_lin = np.linspace(0,10,num=5)
print(ar_lin)


[ 0.   2.5  5.   7.5 10. ]
