In [1]:
import numpy as np

In [4]:
a = np.array([12, 3, 2, 5, 7])
b = np.array([11, 1, 7, 5, 4])
print(a + b)


[23  4  9 10 11]


# indexing

In [5]:
print(a[3])

5


In [7]:
print(b[-3])

7


## slicing

In [9]:
print(a[1:5:1])

[3 2 5 7]


In [10]:
print(a[::-1])

[ 7  5  2  3 12]


## iteration

In [11]:
for i in b:
    print(i)

11
1
7
5
4


In [12]:
x = np.array([[1,3,4],
             [3,5,7]])
print(x)

[[1 3 4]
 [3 5 7]]


In [13]:
for i in x:
    print(i)

[1 3 4]
[3 5 7]


In [14]:
for i in x:
    for k in i:
        print(k)

1
3
4
3
5
7
