In [1]:
import numpy as np

## matrix

In [2]:
var = np.matrix([[1,2,3],[3,4,5]])
print(var)
print(type(var))

[[1 2 3]
 [3 4 5]]
<class 'numpy.matrix'>


In [3]:
var1 = np.array([[1,2,3],[3,4,5]])
print(var1)
print(type(var1))

[[1 2 3]
 [3 4 5]]
<class 'numpy.ndarray'>
