# random

## rand()

In [1]:
import numpy as np

In [3]:
var = np.random.rand(4)
print(var)

[0.86167491 0.45593596 0.12141518 0.31797003]


In [4]:
var1 = np.random.rand(2,6)
print(var1)

[[0.08098585 0.47215104 0.83250255 0.74192336 0.30341705 0.09572926]
 [0.54527948 0.33535543 0.44958175 0.2598259  0.94619155 0.89062515]]


# randn()

In [7]:
var2 = np.random.randn(5)
var3 = np.random.randn(2,5)
print(var2)
print()
print(var3)

[-2.03420691  1.16712677  0.49175734 -1.25564984 -0.65011239]

[[ 3.50095601e-01  2.74444290e-01 -1.08963880e-01  3.92798235e-01
  -4.73671069e-01]
 [ 6.36545048e-05 -1.65385514e+00  1.16023260e+00 -8.98622265e-01
   8.59244130e-01]]


## ranf()

In [10]:
var4 = np.random.ranf(5)
var5 = np.random.ranf((2,4))
print(var4)
print()
print(var5)

[0.75430319 0.079028   0.20461814 0.67087631 0.24182448]

[[0.66973619 0.16016853 0.90275231 0.96695799]
 [0.14897811 0.31599215 0.62999986 0.21266624]]


## randint()

In [13]:
var6 = np.random.randint(4)
var7 = np.random.randint(2,7,10)
print(var6)
print()
print(var7)

2

[2 3 3 5 3 6 4 3 4 2]
