## join array

In [1]:
import numpy as np 

In [7]:
a = np.array([2, 4, 5, 6])
b = np.array([3, 5, 6])

ar = np.concatenate((a, b))
print(ar)

[2 4 5 6 3 5 6]


In [11]:
c = np.array([[2,3],[4,5]])
d = np.array([[1,2],[4,5]])

r = np.concatenate((c, d), axis=0)
print(r)
print()
w = np.concatenate((c, d), axis = 1)
print(w)

[[2 3]
 [4 5]
 [1 2]
 [4 5]]

[[2 3 1 2]
 [4 5 4 5]]


In [16]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([6,7,8,9])
a_new = np.stack((arr1, arr2), axis=1)
print(a_new)
a_new1 =np.hstack((arr1, arr2)) # row
print(a_new1)
a_new2 = np.vstack((arr1, arr2)) # column
print(a_new2)
a_new3 = np.dstack((arr1, arr2)) # height
print(a_new3)

[[1 6]
 [2 7]
 [3 8]
 [4 9]]
[1 2 3 4 6 7 8 9]
[[1 2 3 4]
 [6 7 8 9]]
[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]


## split array

In [24]:
arr5 = np.array([2,13,5,4,7,8,6])
print(arr5)
y = np.array_split(arr5, 2)
print(y)
print()
print(y[0]) #indexing

[ 2 13  5  4  7  8  6]
[array([ 2, 13,  5,  4]), array([7, 8, 6])]

[ 2 13  5  4]
